// projects-data.js — the seven projects, content VERBATIM from
// project-descriptions.md. Prose is preserved exactly, including the honest
// acknowledgement of failure and limitation — that tone is the point.
// Inline **bold** / *italic* markers are rendered by projects.js.
//
// section shape: { h, p: [..paras], list: [..items], blocks: [{ h, p:[..] }] }
// accent = the node's luminous colour, drawn from the cosmic palette.

export const PROJECTS = [
  {
    id: 1,
    num: 'I',
    title: 'Autonomous Poker Dealer',
    subtitle: 'Computer Vision · AI · Robotics Integration',
    tagline: 'Worked in a team to design a robotic arm to deal poker cards, integrating mechanical design and control systems.',
    accent: '#6f86ff',
    images: [{ src: 'assets/images/project1.jpg', alt: 'Autonomous poker-dealing robotic arm' }],
    sections: [
      { h: 'My Role & Perspective', p: [
        'My contribution to this project was primarily focused on the **mechanical design** of the robotic arm. I joined the team at a relatively late stage, at a point where several key hardware components had already been ordered based on an earlier design direction.',
        'The original plan was to construct the arm largely from pre-made components. However, midway through the project, the design scope shifted toward a different arm configuration. At that point, I was tasked with designing a new mechanical layout using components that had been selected for a different concept, with limited briefing on the final intended architecture.',
      ] },
      { h: 'Design Constraints & Challenges', p: [
        'This meant working under unusually rigid constraints: I had to use the available motors, servos, and structural components while simultaneously imagining and defining how the arm should function geometrically and spatially. One of the key requirements was ensuring that the arm could reach across the full width of a poker table to deal cards reliably.',
        'To satisfy the reach requirement, the arm geometry necessarily became long and extended. While this met the workspace objective, it introduced a significant mechanical mismatch: the distal servo motors were **too large and too heavy** relative to their function, and the mass distribution placed excessive load on the base joint.',
      ] },
      { h: 'Why the System Failed', p: [
        'Although the arm could theoretically reach the required workspace when fully extended, the base servo was unable to support the combined weight and moment generated by the upstream motors and arm structure. In practice, the torque requirements exceeded what the base actuator could reliably deliver.',
        'In hindsight, the design failure was not caused by a single poor engineering decision, but by a **system-level mismatch** between actuator selection, mass distribution, and kinematic requirements. The servo motors did not need to be as bulky at the end effector, and a lighter, more hierarchical actuation strategy would have been more appropriate.',
      ] },
      { h: 'Reflection', p: [
        'From my perspective, the core issue was ultimately one of **project management and scope alignment**. There was a substantial disconnect between what components had been procured, what the final system was expected to do, and how those expectations evolved over time.',
        'This experience reinforced an important engineering lesson: even strong subsystem design cannot compensate for unclear requirements and late-stage scope changes. Mechanical systems, in particular, are far less forgiving to iteration than software or perception pipelines.',
      ] },
      { h: 'Key Lessons', list: [
        '**Robotics is systems engineering:** perception can be "correct" while hardware still fails.',
        '**Iteration speed matters:** software iterations are cheap; mechanical iterations are expensive.',
        '**Engineering honesty wins:** documenting failure properly is often more valuable than a demo.',
      ] },
    ],
    links: [
      { label: 'Vision Approach Article', href: 'https://blog.roboflow.com/computer-vision-robotic-poker-dealer/' },
      { label: 'GitHub Repository', href: 'https://github.com/jalliet/poker-robot-arm-24-25' },
      { label: 'LinkedIn Reflection', href: 'https://www.linkedin.com/feed/update/urn:li:activity:7338510947017187328/' },
    ],
  },

  {
    id: 2,
    num: 'II',
    title: 'DMT Gravity-Propelled Car',
    subtitle: 'Mechanical Engineering · Design, Manufacture & Test',
    tagline: 'Design, manufacture, and test of a gravity-powered vehicle under strict performance and cost constraints.',
    accent: '#58c5bb',
    images: [{ src: 'assets/images/project2.jpg', alt: 'Gravity-propelled car with plywood chassis' }],
    sections: [
      { h: 'Project Context', p: [
        'This project was a first-year **Design–Make–Test (DMT)** coursework assignment focused on designing and building a small gravity-propelled vehicle capable of travelling the full length of a 5 m inclined track using only the energy from a falling mass.',
        'The brief intentionally imposed strict constraints on materials, components, and cost, closely mirroring real-world engineering scenarios where performance must be balanced against manufacturability and resource limitations.',
      ] },
      { h: 'My Role & Contributions', p: [
        'My primary responsibility within the group was the **mechanical design and CAD modelling** of the vehicle. This included designing the plywood chassis, assembling the drivetrain using pre-specified components, and producing detailed engineering drawings to support manufacture and assembly.',
        'Although many components were industry-standard and pre-selected, the challenge lay in accurately modelling these parts from catalogue dimensions and integrating them into a coherent, mechanically sound assembly.',
      ] },
      { h: 'Engineering Challenges', p: [
        'The core engineering problem was converting gravitational potential energy into forward motion as efficiently as possible while minimising energy losses due to friction and wheel slip. This required careful consideration of gearbox ratios, wheel dimensions, axle loading, and overall mass distribution.',
        'A key constraint was that once the plywood chassis was cut, its geometry could not be modified. This forced careful upfront design decisions regarding component placement and structural stability.',
      ] },
      { h: 'Analytical Approach', p: [
        'To guide design decisions, theoretical energy balance equations were used to estimate the vehicle\'s final velocity. I implemented these calculations in a Python script, allowing rapid iteration over wheel sizes and gearbox ratios to identify suitable configurations before committing to manufacture.',
      ] },
      { h: 'Reflection & Key Lessons', p: [
        'While the project was relatively simple in scope, it highlighted how even small mechanical systems are governed by trade-offs between performance, robustness, and practicality. The experience reinforced the value of analytical modelling as a decision-making tool rather than a purely academic exercise.',
        'Most importantly, this project served as an introduction to structured engineering thinking: defining constraints, justifying design choices, and accepting that optimal solutions often emerge from compromise rather than idealised theory.',
      ] },
      { h: 'Interactive Assets', list: [
        '**3D Model — Plywood chassis:** the main structural component, primary mounting structure for all drivetrain and support components.',
        '**3D Model — Full vehicle assembly:** integrating standard bearings, fasteners, shafts, and drivetrain components.',
        '**Python modelling tool:** estimates vehicle final velocity by modelling energy transfer, axle load distribution, and rolling friction losses.',
      ] },
    ],
    documents: [
      { label: 'Python velocity model', href: 'assets/code/dmt_velocity_model.py', note: 'Energy-balance script — final velocity vs. wheel size and gearbox ratio.' },
    ],
  },

  {
    id: 3,
    num: 'III',
    title: '3-Axis CNC Positioning System',
    subtitle: 'Mechanical Design Project',
    tagline: 'Embodiment & detailed design of a precision CNC motion system under stiffness and performance constraints.',
    accent: '#8c7cf0',
    images: [{ src: 'assets/images/project3.jpg', alt: '3-axis CNC positioning system design' }],
    sections: [
      { h: 'Project Context', p: [
        'This project was a second-year mechanical engineering coursework assignment involving the complete mechanical design of a **three-axis CNC positioning system** intended for laser-based surface heat treatment of a cylindrical steel workpiece.',
        'The design brief imposed stringent performance requirements, particularly a maximum allowable elastic deflection of ±5 µm per axis, placing stiffness rather than strength at the centre of the design process.',
      ] },
      { h: 'My Role & Contributions', p: [
        'Within the group, my contributions focused on **structural design, component selection, and analytical validation**. I was responsible for key load analyses, stiffness calculations, and the CAD modelling of several subsystems, including structural brackets and motion components.',
        'I also contributed to the production of detailed drawings and technical justification included in the final report, ensuring that design decisions were traceable and defensible.',
      ] },
      { h: 'Engineering Challenges', p: [
        'Unlike strength-governed designs, this system was dominated by elastic deformation limits. Even small geometric changes could result in deflections exceeding the permissible range, requiring careful iteration of cross-sections, spans, and support locations.',
        'Component selection further constrained the design: linear guides, lead screws, motors, and bearings had to be chosen from real catalogues, forcing trade-offs between stiffness, cost, availability, and dynamic performance.',
      ] },
      { h: 'Design Approach', p: [
        'The design process relied on simplified analytical models such as beam bending and plate deflection equations to guide early decisions before refinement in CAD. This approach enabled rapid elimination of unviable configurations prior to detailed modelling.',
        'As the design evolved, changes in one axis often propagated through the entire system, highlighting the interdependence inherent in multi-axis mechanical assemblies.',
      ] },
      { h: 'Reflection & Key Lessons', p: [
        'This project provided a realistic introduction to **stiffness-limited mechanical design** and demonstrated how tight performance tolerances can dominate system architecture. It also reinforced the importance of early analytical reasoning to reduce unnecessary iteration at later stages.',
        'Beyond technical skills, the project highlighted the value of clear documentation and structured justification when working within a team. The experience closely resembled early-stage industrial design work rather than a purely academic exercise.',
      ] },
    ],
    documents: [
      { label: 'Group 28 — Design 2 Project Report', href: 'assets/code/Group 28 Design 2 Project Report.pdf', note: 'Full design report: load analysis, stiffness calculations, and justification.' },
    ],
  },

  {
    id: 4,
    num: 'IV',
    title: 'Hack-A-Bot: Toxic Waste Disposal Rover',
    subtitle: '24-Hour Robotics Hackathon',
    tagline: '24-hour robotics hackathon: design and build a robot capable of transporting a sensor-equipped "toxic waste" barrel across an obstacle course under time pressure.',
    accent: '#e8b06a',
    images: [{ src: 'assets/images/project4.jpg', alt: 'Hack-A-Bot rover with claw and elevator' }],
    sections: [
      { h: 'Project Context', p: [
        'This project was a high-intensity, 24-hour robotics hackathon where the task was to design and build a robot capable of transporting a sensor-equipped "toxic waste" barrel across an obstacle course under time pressure.',
        'The event emphasized rapid prototyping, teamwork, and pragmatic engineering decisions in a fast-paced environment. Our team had to ideate, fabricate, test, and iterate within a single day.',
      ] },
      { h: 'My Role & Contributions', p: [
        'I contributed directly to both the mechanical and systems aspects of the robot: I designed and assembled a stable DC-motor chassis, integrated an **Arduino Uno** with Bluetooth control for remote actuation, and developed a servo-powered claw and lifting mechanism using custom SolidWorks parts.',
        'The mechanical subsystems — particularly the claw and elevator — were designed to handle variable loads with minimal complexity, balancing robustness and rapid manufacturability.',
      ] },
      { h: 'Action & Implementation', list: [
        'Constructed a reliable mobile base using DC motors and lightweight structural materials to navigate the obstacle course.',
        'Programmed wireless control using an Arduino Uno and Bluetooth module, enabling responsive remote operation within the course constraints.',
        'Designed and fabricated servo-actuated claws and an elevator system in SolidWorks, iterating quickly to ensure effective grasping and lifting of the mock barrel.',
      ] },
      { h: 'Result & Reflection', p: [
        'By the end of the 24-hour period, our team delivered a functional rover featuring an innovative claw-and-elevator system capable of picking up and transporting the target object across terrain obstacles. The project was an excellent test of multidisciplinary integration under extreme time pressure.',
        'More than a completed robot, the event was a lesson in **collaboration**, rapid engineering decision-making, and resilience. Applying mechanical design principles in a constrained timeframe taught me a great deal about prioritising robustness over polish, anticipating failure modes quickly, and communicating effectively within a team.',
      ] },
    ],
    links: [
      { label: 'LinkedIn reflection', href: 'https://www.linkedin.com/posts/shaswat-khowala_last-weekend-i-was-privileged-to-have-participated-ugcPost-7313231820194504704-6LUE' },
    ],
  },

  {
    id: 5,
    num: 'V',
    title: 'Gear-Prix: Drivetrain Design Challenge',
    subtitle: '12-Hour Mechanical Engineering Competition',
    tagline: '12-hour mechanical engineering competition: design, build, and race a small electric car with a focus on drivetrain optimisation.',
    result: '2nd overall · score 89.6',
    accent: '#e0639c',
    images: [
      { src: 'assets/images/project5.jpg', alt: 'Gear-Prix electric car build' },
      { src: 'assets/images/project5_2.jpg', alt: 'Gear-Prix drivetrain detail' },
    ],
    video: { src: 'assets/vids/GearPrixVid.mp4', alt: 'Gear-Prix car racing' },
    sections: [
      { h: 'Project Context', p: [
        'This project was a time-constrained mechanical engineering competition organised by The University of Manchester Motorsport Society, where teams were tasked with designing, building, and racing a small electric car within a strict 12-hour window. With the full CAD design and manufacturing process compressed into a single day, the event tested rapid engineering decision-making.',
        'The challenge focused on drivetrain optimisation under real-world constraints, including limited power, fixed components, and a competitive scoring system. Performance on the track depended heavily on early engineering decisions rather than post-build iteration.',
      ] },
      { h: 'My Role & Contributions', p: [
        'I played a key role in the mechanical design and drivetrain decision-making for the car, with a particular focus on selecting an appropriate gear reduction. This involved estimating the final vehicle mass, analysing torque and traction requirements, and balancing acceleration and top speed to suit the expected track conditions.',
        'The final design used a **1:2.5 gear reduction**, chosen through calculation rather than trial-and-error. As a result, the drivetrain performed as intended from the outset and required no last-minute adjustments during testing or racing.',
      ] },
      { h: 'Action & Implementation', list: [
        'Designed and assembled a lightweight chassis using a plywood base, steel axle, and toy car wheels provided by the organisers.',
        'Implemented a drivetrain powered by a **Titan 29T DC motor**, transmitting power through custom 3D-printed spur gears.',
        'Designed and manufactured custom components including a motor mount, axle coupler, front axle bracket, and circlips to control axial motion.',
        'Fabricated custom rear axle brackets by bending and drilling sheet metal to ensure proper alignment and structural stability.',
      ] },
      { h: 'Result & Reflection', p: [
        'The completed car performed reliably throughout the race and finished **2nd overall**, achieving a final score of **89.6**. The drivetrain delivered a strong balance between acceleration and speed, validating the initial calculations and design assumptions.',
        'This project reinforced the importance of deliberate engineering decisions early in the design process. With limited time and no margin for extensive iteration, success depended on getting the fundamentals right from the start.',
      ] },
    ],
    links: [
      { label: 'LinkedIn post', href: 'https://www.linkedin.com/posts/ahmedmishqat_over-the-past-two-days-our-team-took-part-activity-7425312572364464128-3-dd' },
    ],
  },

  {
    id: 6,
    num: 'VI',
    title: 'IMechE Design Challenge 2026',
    subtitle: 'Autonomous Robotics · SolidWorks FEA · Arduino · Mechatronics',
    team: 'Unlimited Rice Pudding · NW Regional Heat Winners → Nationals',
    tagline: 'Autonomous external pipe-climbing robot. Won the North West Regional heat, advancing to nationals.',
    result: 'NW Regional Winners → Nationals',
    accent: '#e8c28a',
    images: [
      { src: 'assets/images/project6_1.jpeg', alt: 'Pipe-climbing robot' },
      { src: 'assets/images/project6_2.webp', alt: 'Pipe-climbing robot on a vertical pipe' },
    ],
    sections: [
      { h: 'The Challenge', p: [
        'The 2026 IMechE Design Challenge tasked teams with designing and building an **autonomous external pipe-climbing robot** capable of navigating vertical industrial pipe structures without human intervention. Our team — Unlimited Rice Pudding — entered the North West Regional heat. We won, and advanced to the national competition.',
      ] },
      { h: 'Concept & Architecture', p: [
        'The fundamental problem with pipe-climbing robots is the grip-mobility trade-off: the tighter you clamp to climb, the harder it is to move. From the outset I pushed for a **clamping-and-climbing architecture** — alternating clamp-then-inch sequences, similar to an inchworm — rather than a continuous-drive approach. This gave us more predictable force profiles and let us design the clamping and driving subsystems with well-defined load cases rather than simultaneous demands.',
        'The mechanical core is a symmetric clamping jaw system actuated by a dedicated motor, bearing against the pipe to generate the normal force needed for the drive wheels to develop traction. Getting that normal force calculation right early was non-trivial — too little and the robot slips; too much and the drive motor can\'t overcome the resulting friction on the pipe surface.',
      ] },
      { h: 'My Contributions', blocks: [
        { h: 'Mechanical Design & Chassis', p: [
          'I designed the main chassis in SolidWorks: the structural frame, motor mounting points, and a **custom electronics enclosure** that protected the Arduino and power electronics from handling and vibration loads during climbing. The enclosure also served as a tidy mounting surface for wiring — something that matters more than you\'d think in a competition demo environment.',
        ] },
        { h: 'Topology Optimisation & FEA', p: [
          'On structural components where mass was a direct performance cost — higher mass means greater required clamping force, which drives up motor size — I ran **topology optimisation in SolidWorks Simulation**, followed by FEA validation under expected load cases. This reduced structural component mass by over 30% while keeping stress well within material limits. The numbers held up; nothing cracked under competition conditions.',
        ] },
        { h: 'Drive & Clamp Motor Selection', p: [
          'Motor selection was done analytically. I worked through the torque and load calculations for both the drive and clamping motors, accounting for pipe surface friction coefficient, estimated robot weight, required climb rate, and the safety factor that competition conditions demand.',
        ] },
        { h: 'Arduino Control Architecture & Dead-Reckoning', p: [
          'The original plan used an HC-SR04 ultrasonic sensor for positional feedback during climbing. In testing, the sensor proved unreliable at the distances and geometries involved — reflections from the cylindrical pipe surface scattered the return signal and gave inconsistent readings at range.',
          'Rather than spend competition preparation time debugging sensor physics, I **redesigned the control architecture around dead-reckoning using motor pulse timing**. By counting encoder-equivalent pulses and correlating them to measured wheel travel, we achieved positioning accuracy competitive with what the sensor was supposed to deliver — arguably more repeatable, since it removed an environmental variable entirely. The lesson: when a sensor behaves unexpectedly, consider whether the sensor is actually necessary.',
        ] },
      ] },
      { h: 'Reflection', p: [
        'Winning the NW regional heat was satisfying, but what I took from this project more than the result was the value of **committing to an architecture early**. Once we settled on clamping-and-climbing instead of continuous-drive, every subsequent decision — motor sizing, control logic, structural layout — became significantly cleaner. Ambiguity in the concept phase propagates into everything downstream.',
        'The dead-reckoning pivot was a good reminder that the "proper" solution isn\'t always the most robust one. Engineering in a competition context has to account for the fact that you\'ll be demonstrating in conditions you can\'t fully control. Removing the sensor dependency made the system more deterministic, not less capable.',
      ] },
    ],
    documents: [
      { label: 'Technical Presentation', href: 'assets/files/project6_presentation.pdf', note: 'Slides delivered at the NW Regional heat: concept, design, and validation.' },
      { label: 'Power Systems Calculations', href: 'assets/files/project6_calc.pdf', note: 'Analytical torque and load analysis used for drive and clamping motor selection.' },
    ],
  },

  {
    id: 7,
    num: 'VII',
    title: 'IMechE CADathon 2026',
    subtitle: 'SolidWorks · Mechanical Design · Design Sprint · SDG 11',
    team: '8-Hour Competitive Design Sprint · 2nd Place, Sustainability Category',
    tagline: '8-hour design sprint. Pedal-powered, gamified aluminium can crusher targeting SDG 11.',
    result: '2nd place · Sustainability',
    accent: '#5fc9a6',
    images: [
      { src: 'assets/images/project7_1.jpeg', alt: 'CrushIt pedal-powered can crusher' },
      { src: 'assets/images/project7_2.jpeg', alt: 'CrushIt CAD render' },
    ],
    sections: [
      { h: 'The Brief', p: [
        'The IMechE CADathon is an 8-hour competitive design sprint where teams receive a brief on the day and must design, model, and present a complete engineering solution within the window. Our 2026 brief centred on **SDG 11 — Sustainable Cities and Communities**. No prior preparation, no pre-built models. Everything from concept to CAD to presentation in eight hours.',
      ] },
      { h: 'The Problem We Chose to Solve', p: [
        'Aluminium cans are one of the most recyclable materials on earth — yet at high-footfall events like festivals, sports venues, and public spaces, recycling rates are consistently poor. The standard explanation is apathy. We disagreed with that framing.',
        'Our analysis was simpler: **passive infrastructure makes recycling the inconvenient choice**. Bins are identical. There\'s no feedback, no engagement, no reason to prefer the recycling option over the bin nearest to you. If recycling were the *fun* choice, behaviour would follow. That became the brief we gave ourselves.',
      ] },
      { h: 'CrushIt — The Concept', p: [
        'CrushIt is a **pedal-powered, gamified aluminium can crusher** designed for deployment at high-footfall public events. The user steps on a foot pedal, the can crushes, a mechanical counter increments. Two units sit side-by-side, each representing a team — the demo concept being a Messi vs Ronaldo rivalry. Live crush counts are displayed on each side. Recycling becomes a competitive game.',
        'The judging panel specifically cited the gamified dual-sided engagement mechanic as the key differentiator in our score. That was gratifying — it was the first idea I put on paper when the brief dropped.',
      ] },
      { h: 'Mechanical Design', p: [
        'The entire machine is **fully passive — zero electricity**. Everything is mechanical:',
      ], list: [
        '**Foot-pedal toggle linkage** — delivers crushing force through a mechanical advantage linkage, returning to the ready position under spring tension.',
        '**Upper spike platform** — pre-punctures the can at the top before the main crush begins, safely releasing pressurised carbonation before the can deforms. A sealed, suddenly-crushed can can behave unpredictably; this removes that risk.',
        '**Grid lower platform with liquid drainage tray** — open-grid geometry lets residual liquid drain passively, keeping the mechanism and floor clean.',
        '**Inclined exit floor** — crushed cans roll to one side automatically, clearing the crushing zone for the next can without user intervention.',
        '**Mechanical safety lid interlock** — the crushing sequence can only initiate when the lid is correctly closed, preventing hand injuries. Fully mechanical — no electronics, no software failure modes.',
      ] },
      { h: 'My Contributions', p: [
        'I originated the CrushIt concept and identified the framing problem — that poor recycling at events is an infrastructure and engagement problem, not an apathy problem. The gamification mechanic (dual-sided competitive engagement, live counter) was my core design contribution, and the one the judges called out specifically.',
        'Beyond concept, I led all SolidWorks CAD modelling across the eight hours and built the final presentation deck within the same window. In a time-constrained format, the ability to CAD and communicate simultaneously is where competitions are won or lost.',
      ] },
      { h: 'Reflection', p: [
        'Second place in a sustainability design sprint in eight hours is a decent result. But what I took from it was less about the placement and more about design process under genuine time pressure.',
        'The instinct under time pressure is to jump to solutions — to start modelling before you\'ve understood the problem. Teams that do that tend to produce technically competent designs that don\'t land with judges, because the problem framing is soft. Spending the first thirty minutes challenging the brief\'s implicit assumptions (why is recycling low? is it actually apathy?) produced a sharper concept than we\'d have gotten by immediately going to CAD.',
        'The all-mechanical, zero-electricity constraint was a deliberate choice, not a limitation. It meant the design had no power dependency, no software failure modes, and was immediately manufacturable from standard materials. Simplicity in mechanical design is underrated.',
      ] },
    ],
    documents: [
      { label: 'CADathon Presentation', href: 'assets/files/project7_presentation.pdf', note: 'Full deck: concept, CAD renders, mechanical drawings, and SDG 11 impact justification.' },
    ],
  },
];
